[pytest]
addopts = --verbose -s --tb=short --alluredir=allure-results
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
markers =
    unit: Unit tests
    e2e: End-to-end tests
    smoke: Quick smoke tests
    slow: Slow running tests
