version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(levelname)-5s - %(message)s'
    datefmt: "%Y-%m-%d %H-%M-%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  test_log:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'test.log'
    encoding: utf8

root:
  level: DEBUG
  handlers: [ console, test_log ]
